// Create user
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "abi4",
  "email": "abi4@gmail.com",
  "password": "123456",
  "role": "userfood"
}

###
// Get ALL Users
GET http://localhost:5000/users

###
// Get Single Users
GET http://localhost:5000/users/c1e58026-b3d2-4d51-bd7e-93d300cf12d3

###
// Update user
PATCH  http://localhost:5000/users/e9e5bcb2-073e-4092-8b1c-88d4edb2077f
Content-Type: application/json

{
  "name": "hasbibev",
  "email": "hasbibev@gmail.com",
  "password": "123456",
  "role": "userbev"
}

###
// Delete user
DELETE http://localhost:5000/users/e9e5bcb2-073e-4092-8b1c-88d4edb2077f

###
// Login user
POST   http://localhost:5000/login
Content-Type: application/json

{
  "email": "hasbi@gmail.com",
  "password": "123456"
}

###
// Me
GET  http://localhost:5000/me

###
// Logout
DELETE http://localhost:5000/logout

###
// Get All Bevs
GET http://localhost:5000/bevs

###
// Get Single Bevs
GET http://localhost:5000/bevs/35dcbc7d-82bb-4b62-bb0f-d9ca34b45cb4

###
// Post Data Bev
POST   http://localhost:5000/bevs
Content-Type: application/json

{
  "name": "Minuman 1",
  "price": 3000,
  "ings": "teh manis",
  "img": "gambar teh",
  "highlight": "Green tea",
  "brew": "1liter garam",
  "desc": "manis banget",
  "moods": ["Disgust", "Angry"]
}

###
// Update Data Bev
PATCH   http://localhost:5000/bevs/51f89aaf-5e9c-4e81-8bef-fe2d90cf18d7
Content-Type: application/json

{
  "name": "Minuman 3 up",
  "price": 333333333,
  "ings": "teh manis up",
  "img": "gambar teh up",
  "highlight": "Green tea up",
  "brew": "1liter garam up",
  "desc": "manis banget up",
  "moods": ["Disgust", "Surprise"]
}

###
// Delete Data Bev
DELETE  http://localhost:5000/bevs/51f89aaf-5e9c-4e81-8bef-fe2d90cf18d7

###
// Get All Food
GET http://localhost:5000/foods

###
// Get Single Food
GET http://localhost:5000/foods

###
// Post Data Food
POST   http://localhost:5000/foods
Content-Type: application/json

{
  "name": "Makanan 3",
  "price": 3000,
  "ings": "makanan manis",
  "img": "gambar makanan",
  "desc": "enak bet"
}

###
// Update Data Food
PATCH   http://localhost:5000/foods
Content-Type: application/json

{
  "name": "Makanan 3",
  "price": 3000,
  "ings": "makanan manis",
  "img": "gambar makanan",
  "desc": "enak bet"
}

###
// Delete Data Food
DELETE  http://localhost:5000/foods

###
// Get All Fp
GET http://localhost:5000/foodPairings

###
// Get Single Fp
GET http://localhost:5000/foodPairings

###
// Post Data Fp
POST   http://localhost:5000/foodPairings
Content-Type: application/json

{
  "bevId": "6",
  "foodId": "1"
}

###
// Update Data Fp
PATCH   http://localhost:5000/foodPairings
Content-Type: application/json

{
  "name": "Mkakan 2 update",
  "price": 322222,
  "ings": "teh manis",
  "img": "gambar teh"
}

###
// Delete Data Fp
DELETE  http://localhost:5000/foodPairings